pwm-fan-control.py: TypeError
Resolved the following error:

TypeError: can only concatenate str (not "int") to str [duplicate]

OFF_THRESHOLD and ON_THRESHOLD must be converted to a string with str() function when used in the concatenated string.